version: '2'

services:
  server:
    image: custom-goku
    network_mode: ${NETWORK_MODE}
    ports:
    - 8080
    environment:
      - GOKU_RUNMODE=${GOKU_RUNMODE}

  proxy:
    image: custom-nginx
    network_mode: ${NETWORK_MODE}
    volumes:
    - ./logs
    ports:
    - 80
    links:
      - server:server